import tsPlugin from '@typescript-eslint/eslint-plugin'
import tsParser from '@typescript-eslint/parser'
import prettierConfig from 'eslint-config-prettier'
import banPlugin from 'eslint-plugin-ban'
import etcPlugin from 'eslint-plugin-etc'
import importPlugin from 'eslint-plugin-import'
import unicornPlugin from 'eslint-plugin-unicorn'
import unusedImportsPlugin from 'eslint-plugin-unused-imports'

const baseRules = {
    'arrow-body-style': 'error',
    'arrow-parens': ['error', 'always'],
    'callback-return': 'error',
    complexity: ['warn', { max: 15 }],
    'constructor-super': 'error',
    curly: 'error',
    'dot-notation': 'error',
    eqeqeq: 'error',
    'eol-last': 'error',
    'guard-for-in': 'error',
    'linebreak-style': 'off',
    'max-classes-per-file': 'off',
    'new-parens': 'error',
    'newline-per-chained-call': 'off',
    'no-bitwise': 'off',
    'no-caller': 'error',
    'no-cond-assign': 'error',
    'no-console': 'warn',
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-debugger': 'error',
    'no-duplicate-imports': 'error',
    'no-empty': 'error',
    'no-else-return': ['error', { allowElseIf: false }],
    'no-eval': 'error',
    'no-extra-bind': 'error',
    'no-extra-semi': 'off',
    'no-fallthrough': 'off',
    'no-floating-decimal': 'error',
    'no-inner-declarations': 'off',
    'no-invalid-this': 'off',
    'no-irregular-whitespace': 'error',
    'no-lonely-if': 'error',
    'no-magic-numbers': 'off',
    'no-multiple-empty-lines': ['error', { max: 1 }],
    'no-new-wrappers': 'error',
    'no-redeclare': 'off',
    'no-sparse-arrays': 'error',
    'no-sync': ['error', { allowAtRootLevel: true }],
    'no-template-curly-in-string': 'error',
    'no-throw-literal': 'error',
    'no-undef-init': 'error',
    'no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'no-unsafe-finally': 'error',
    'no-unsafe-optional-chaining': 'off',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'off',
    'no-var': 'error',
    'no-void': 'error',
    'object-shorthand': 'error',
    'one-var': ['error', 'never'],
    'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
    'prefer-const': ['error', { destructuring: 'all' }],
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'off',
    quotes: 'off', // Prettier handles this
    radix: 'error',
    'require-await': 'error',
    semi: 'off', // Prettier handles this
    'spaced-comment': ['error', 'always', { line: { markers: ['/'] } }],
    'sort-imports': 'off',
    'use-isnan': 'error',
    'valid-typeof': 'off',
    yoda: 'error',

    // Import rules
    'import/extensions': ['error', 'never'],
    'import/no-deprecated': 'warn',
    'import/no-unused-modules': 'error',
    'import/no-cycle': 'off',
    'import/no-self-import': 'error',
    'import/no-dynamic-require': 'error',
    'import/no-useless-path-segments': 'error',
    'import/no-duplicates': 'error',
    'import/no-default-export': 'error',
    'import/order': [
        'error',
        {
            groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
            'newlines-between': 'always',
            alphabetize: {
                order: 'asc',
                caseInsensitive: true,
            },
        },
    ],
    'import/no-unresolved': 'off',
    'import/default': 'off',
    'import/named': 'off',
    'import/namespace': 'off',

    'id-length': [
        'error',
        {
            min: 3,
            properties: 'never',
            exceptions: ['to', 'as', 'id', 'it', 'fs', 'os', 'H', 'a', 'b'],
        },
    ],

    'unicorn/filename-case': ['error', { cases: { camelCase: true, pascalCase: true, kebabCase: true } }],
    'unicorn/no-process-exit': 'off',
    'unicorn/no-null': 'off',
    'unicorn/no-fn-reference-in-iterator': 'off',
    'unicorn/no-reduce': 'off',
    'unicorn/no-useless-undefined': 'off',
    'unicorn/prefer-number-properties': 'off',
    'unicorn/custom-error-definition': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/number-literal-case': 'off',
    'unicorn/numeric-separators-style': 'off',
    'unicorn/prefer-switch': 'off',
    'unicorn/prefer-spread': 'off',
    'unicorn/template-indent': 'off',
    'unicorn/prefer-export-from': 'off',
    'unicorn/explicit-length-check': 'off',
    'unicorn/prefer-date-now': 'off',
    'unicorn/no-await-expression-member': 'off',
    'unicorn/prefer-dom-node-text-content': 'off',
    'unicorn/consistent-destructuring': 'off',
    'unicorn/no-new-array': 'off',
    'unicorn/prefer-ternary': 'off',
    'unicorn/prefer-dom-node-dataset': 'off',
    'unicorn/no-useless-spread': 'off',
    'unicorn/no-lonely-if': 'off',
    'unicorn/prefer-array-some': 'off',
    'unicorn/prefer-native-coercion-functions': 'off',
    'unicorn/relative-url-style': 'off',
    'unicorn/prefer-array-flat-map': 'off',
    'unicorn/prefer-node-protocol': 'off',
    'unicorn/prefer-module': 'off',
    'unicorn/no-useless-promise-resolve-reject': 'off',
    'unicorn/no-array-method-this-argument': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/import-style': 'off',
    'unicorn/no-array-push-push': 'off',
    'unicorn/no-useless-switch-case': 'off',
    'unicorn/prefer-regexp-test': 'off',
    'unicorn/no-object-as-default-parameter': 'off',
    'unicorn/prefer-code-point': 'off',
    'unicorn/prefer-object-from-entries': 'off',
    'unicorn/prefer-math-trunc': 'off',
    'unicorn/text-encoding-identifier-case': 'off',
    'unicorn/no-unreadable-iife': 'off',
    'unicorn/error-message': 'off',
    'unicorn/no-thenable': 'off',
    'unicorn/prefer-array-index-of': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/no-for-loop': 'off',
    'unicorn/prefer-includes': 'off',
    'unicorn/prefer-starts-ends-with': 'off',

    'unused-imports/no-unused-imports': 'error',
    'unused-imports/no-unused-vars': 'off',
}

export default [
    {
        ignores: ['node_modules', 'dist'],
    },
    {
        files: ['**/*.js'],
        languageOptions: {
            parserOptions: {
                ecmaVersion: 'latest',
                sourceType: 'module',
            },
            globals: {
                globalThis: false,
            },
        },
        plugins: {
            ban: banPlugin,
            import: importPlugin,
            unicorn: unicornPlugin,
            'unused-imports': unusedImportsPlugin,
        },
        rules: {
            ...baseRules,
            'ban/ban': [
                'error',
                {
                    name: ['*', 'forEach'],
                    message: 'Use a for-of loop instead',
                },
                {
                    name: ['describe', 'only'],
                    message: "Don't forget to remove .only before committing",
                },
                {
                    name: ['it', 'only'],
                    message: "Don't forget to remove .only before committing",
                },
                {
                    name: ['test', 'only'],
                    message: "Don't forget to remove .only before committing",
                },
            ],
            'no-restricted-imports': [
                'error',
                {
                    paths: [
                        {
                            name: 'lodash',
                            importNames: ['isArray'],
                            message: 'Use Array.isArray instead.',
                        },
                    ],
                },
            ],
        },
    },
    {
        files: ['**/*.ts'],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                ecmaVersion: 'latest',
                sourceType: 'module',
                project: './tsconfig.eslint.json',
            },
            globals: {
                globalThis: false,
            },
        },
        plugins: {
            '@typescript-eslint': tsPlugin,
            ban: banPlugin,
            etc: etcPlugin,
            import: importPlugin,
            unicorn: unicornPlugin,
            'unused-imports': unusedImportsPlugin,
        },
        rules: {
            ...baseRules,
            'ban/ban': [
                'error',
                {
                    name: ['*', 'forEach'],
                    message: 'Use a for-of loop instead',
                },
                {
                    name: ['describe', 'only'],
                    message: "Don't forget to remove .only before committing",
                },
                {
                    name: ['it', 'only'],
                    message: "Don't forget to remove .only before committing",
                },
                {
                    name: ['test', 'only'],
                    message: "Don't forget to remove .only before committing",
                },
            ],
            'no-restricted-imports': [
                'error',
                {
                    paths: [
                        {
                            name: 'lodash',
                            importNames: ['isArray'],
                            message: 'Use Array.isArray instead.',
                        },
                    ],
                },
            ],

            '@typescript-eslint/no-var-requires': 'error',
            '@typescript-eslint/prefer-regexp-exec': 'off',
            '@typescript-eslint/no-unsafe-call': 'error',
            '@typescript-eslint/no-unsafe-member-access': 'error',
            '@typescript-eslint/no-unsafe-return': 'error',
            '@typescript-eslint/no-unsafe-assignment': 'error',
            '@typescript-eslint/no-unsafe-argument': 'error',
            '@typescript-eslint/no-namespace': 'off',
            '@typescript-eslint/no-unnecessary-type-constraint': 'off',

            '@typescript-eslint/adjacent-overload-signatures': 'error',
            '@typescript-eslint/array-type': 'error',
            '@typescript-eslint/await-thenable': 'error',
            '@typescript-eslint/no-restricted-types': 'error',
            '@typescript-eslint/naming-convention': 'off',
            '@typescript-eslint/explicit-function-return-type': [
                'error',
                { allowExpressions: true, allowTypedFunctionExpressions: true, allowHigherOrderFunctions: true },
            ],
            '@typescript-eslint/explicit-member-accessibility': ['error', { overrides: { constructors: 'no-public' } }],
            '@typescript-eslint/indent': 'off',
            '@typescript-eslint/interface-name-prefix': 'off',
            '@typescript-eslint/member-delimiter-style': 'off',
            '@typescript-eslint/member-ordering': 'off',
            '@typescript-eslint/no-empty-interface': 'off',
            '@typescript-eslint/no-empty-function': ['error', { allow: ['arrowFunctions'] }],
            '@typescript-eslint/no-explicit-any': 'error',
            '@typescript-eslint/no-extraneous-class': 'error',
            '@typescript-eslint/no-for-in-array': 'error',
            '@typescript-eslint/no-floating-promises': 'error',
            '@typescript-eslint/no-inferrable-types': ['error', { ignoreParameters: true }],
            '@typescript-eslint/no-misused-new': 'error',
            '@typescript-eslint/no-misused-promises': 'error',
            '@typescript-eslint/no-non-null-assertion': 'warn',
            '@typescript-eslint/no-unnecessary-condition': 'off',
            '@typescript-eslint/consistent-type-assertions': [
                'error',
                { assertionStyle: 'as', objectLiteralTypeAssertions: 'never' },
            ],
            '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
            '@typescript-eslint/no-base-to-string': 'error',
            '@typescript-eslint/no-parameter-properties': 'off',
            '@typescript-eslint/no-require-imports': 'error',
            '@typescript-eslint/no-unnecessary-qualifier': 'warn',
            '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    varsIgnorePattern: '^_',
                    args: 'after-used',
                    argsIgnorePattern: '^_',
                    ignoreRestSiblings: true,
                },
            ],
            '@typescript-eslint/no-use-before-define': 'off',
            '@typescript-eslint/no-useless-constructor': 'error',
            '@typescript-eslint/prefer-as-const': 'error',
            '@typescript-eslint/prefer-for-of': 'error',
            '@typescript-eslint/prefer-string-starts-ends-with': 'error',
            '@typescript-eslint/prefer-function-type': 'error',
            '@typescript-eslint/prefer-includes': 'error',
            '@typescript-eslint/prefer-namespace-keyword': 'error',
            '@typescript-eslint/prefer-optional-chain': 'error',
            '@typescript-eslint/prefer-nullish-coalescing': 'warn',
            '@typescript-eslint/type-annotation-spacing': 'off',
            '@typescript-eslint/triple-slash-reference': 'error',
            '@typescript-eslint/restrict-template-expressions': 'off',
            '@typescript-eslint/return-await': 'error',
            '@typescript-eslint/unbound-method': 'warn',
            '@typescript-eslint/unified-signatures': 'error',

            'no-undef': 'off',
            'no-dupe-class-members': 'off',
        },
    },
    {
        files: ['**/*.d.ts', 'eslint.config.js', 'prettier.config.js'],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                ecmaVersion: 'latest',
                sourceType: 'module',
                project: './tsconfig.eslint.json',
            },
        },
        plugins: {
            '@typescript-eslint': tsPlugin,
        },
        rules: {
            'no-var': 'off',
            '@typescript-eslint/explicit-member-accessibility': 'off',
            'id-length': 'off',
            'import/no-default-export': 'off',
        },
    },
    {
        files: ['**/*.test.ts'],
        rules: {
            '@typescript-eslint/explicit-function-return-type': 'off',
            'unicorn/consistent-function-scoping': 'off',
            '@typescript-eslint/no-floating-promises': 'off',
        },
    },
    prettierConfig,
]
